#!/bin/bash

if ! declare -f __prompt_command_wrapper > /dev/null; then
    __prompt_modules=()
    __run_prompt_modules() {
        for func in "${__prompt_modules[@]}"; do $func; done
        if [[ -z "$__ORIGINAL_PS1" ]]; then
            __ORIGINAL_PS1="$PS1"
            local _regex='(.*)(\\\$|\$|\\#|\#)(.*)$'
            if [[ "$__ORIGINAL_PS1" =~ $_regex ]]; then
                __BASE_PS1_PREFIX="${BASH_REMATCH[1]}"
                __BASE_PS1_SUFFIX="${BASH_REMATCH[2]}${BASH_REMATCH[3]}"
            else
                __BASE_PS1_PREFIX="$__ORIGINAL_PS1"
                __BASE_PS1_SUFFIX=""
            fi
        fi
        PS1="${__git_info}${__BASE_PS1_PREFIX}${__exe_time_str}${__exe_status_color}${__BASE_PS1_SUFFIX}\[\e[0m\]"
    }
    __prompt_command_wrapper() {
        __last_exit_code=$?
        __is_in_prompt_command=1
        [[ -n "$__original_prompt_command" ]] && eval "$__original_prompt_command"
        __run_prompt_modules
        unset __is_in_prompt_command
        unset __timer
    }
    if [[ "$PROMPT_COMMAND" != *"__prompt_command_wrapper"* ]]; then
        if [[ "$PROMPT_COMMAND" != "__prompt_command_wrapper" ]]; then
            __original_prompt_command="${PROMPT_COMMAND:-:}"
        fi
        PROMPT_COMMAND="__prompt_command_wrapper"
    fi
fi
if ! declare -f __add_prompt_module > /dev/null; then
    __add_prompt_module() {
        for func in "${__prompt_modules[@]}"; do [[ "$func" == "$1" ]] && return; done
        __prompt_modules+=("$1")
    }
fi

__update_exe_status() {
    if (( __last_exit_code == 0 )); then
        __exe_status_color="\[\e[32m\]" # Green
    else
        __exe_status_color="\[\e[31m\]" # Red
    fi
}
__add_prompt_module "__update_exe_status"
